### ISSUE TITLE
Does this conflict with airplane mode?

### ISSUE THREAD

**Issue by jamesrisberg** [chriscct7/remove-updates#1]
I am using the airplane mode plugin, does this work with it?

**Comment by chriscct7** [comment]
No actually, I merged the code into Airplane mode during the 0.4 release

**Comment by jamesrisberg** [comment]
Does the airplane mode plugin remove the ability to update translations?

**Comment by chriscct7** [comment]
Yes, it turns that off by default, however you can turn that back on if you want

**Comment by jamesrisberg** [comment]
How would I go about doing that?

**Comment by chriscct7** [comment]
You can find the filter in the airplane mode plugin and then do the opposite.

**Comment by chriscct7** [comment]
So its doing a remove action, so what you would do is add_action with the same arguemnts

**Comment by jamesrisberg** [comment]
Where do I put that code?

**Comment by chriscct7** [comment]
You can put it in the functions.php file. That's probably the easiest

**Comment by jamesrisberg** [comment]
If I do that though, won't it prevent me from doing automatic updates to my WordPress theme?

**Comment by chriscct7** [comment]
Yes, if you want you can use the plugin called Pluginception to make a custom plugin and put it in there

**Comment by jamesrisberg** [comment]
Ok great thanks!

**Comment by chriscct7** [comment]
Not a problem!
