### ISSUE TITLE
Does WordPress automatically disabled updates on dev sites?

### ISSUE THREAD

**Issue by jamesrisberg** [chriscct7/remove-updates#2]
Just had this thought

**Comment by chriscct7** [comment]
Actually, it sorta does. If it can detect you are in some sort of version control system, then yes it will turn them off

**Comment by chriscct7** [comment]
That being said, it does not turn them off on localhost, so that can get super annoying if you are on a plane or have a slow internet connection

**Comment by jamesrisberg** [comment]
Yeah, my internet connection is kinda slow. So does this stop third party plugins from updating?

**Comment by chriscct7** [comment]
Yes, if they are using the WordPress core update module, they will be disabled automatically

**Comment by jamesrisberg** [comment]
Are there any major plugins that don't?

**Comment by chriscct7** [comment]
To my knowledge I think no, but Gravity Forms and WPMU might not

**Comment by jamesrisberg** [comment]
I use alot of WPMU plugins. How would I find out if they did?

**Comment by chriscct7** [comment]
If you're a developer, you can look for the presence of an extended update module. If not, contact WPMU

**Comment by chriscct7** [comment]
Its probably easier to just contact them though, as their codebases are always kind of large

**Comment by jamesrisberg** [comment]
So last question, is Airplane mode distributed on WordPress.org?

**Comment by chriscct7** [comment]
No it's not, you'll need to get it from norcross's github page

**Comment by chriscct7** [comment]
That being said I think he's looking at WP distribution soon

**Comment by jamesrisberg** [comment]
Ok cool thanks

**Comment by chriscct7** [comment]
Not a problem. I think I'll delete this repo now that it's merged into norcross/airplane-mode
